---
collections:
  Trending:
    trakt_chart:
      chart: trending
      limit: 100
    sort_title: "# 00 Trending"
    collection_order: custom
    sync_mode: sync
    summary: Movies Trending across the internet
    url_background: https://i.imgur.com/SOVfrIq.png
    url_poster: https://i.imgur.com/4vpMZoA.png
    visible_home: true
    visible_shared: true
    visible_library: true


  Popular:
    trakt_chart:
      chart: popular
      time_period: weekly
      limit: 100
    sort_title: "# 01 Popular"
    collection_order: custom
    sync_mode: sync
    summary: Popular Movies across the internet
    url_background: https://i.imgur.com/SOVfrIq.png
    url_poster: https://i.imgur.com/4cI2Jg4.png
    visible_home: false
    visible_shared: true
    visible_library: true
