templates:
  Studio:
    optional:
      - company
    tmdb_company: <<company>>
    sort_title: +25_<<collection_name>>
    collection_mode: hide
    sync_mode: sync
    smart_label: release.desc
    visible_home: false
    visible_shared: true
    visible_library: true
collections:
  Marvel Studios:
    trakt_list: https://trakt.tv/users/martheo/lists/marvel?sort=rank,asc
    sort_title: +25_Marvel Studios
    collection_mode: hide
    sync_mode: sync
    smart_label: release.desc
    url_poster: https://theposterdb.com/api/assets/53017
  Pixar:
    template: { name: Studio, company: 3 }
    url_poster: https://theposterdb.com/api/assets/4767
  Walt Disney Pictures:
    template: { name: Studio, company: 2 }
    url_poster: https://theposterdb.com/api/assets/48748
  Studio Ghibli:
    template: { name: Studio, company: 10342 }
    url_poster: https://theposterdb.com/api/assets/51610
