collections:
  Trending:
    trakt_chart:
      chart: trending
      limit: 100
    sort_title: "# 00 Trending"
    collection_order: custom
    sync_mode: sync
    url_poster: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Posters/Charts/Trending_Weekly.JPG
    visible_home: true
    visible_shared: true
    visible_library: true

  Popular:
    trakt_chart:
      chart: watched
      time_period: weekly
      limit: 100
    sort_title: "# 01 Popular"
    collection_order: custom
    sync_mode: sync
    url_poster: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Posters/Charts/Popular_Now.JPG
    visible_home: false
    visible_shared: true
    visible_library: true

  IMDb Top 250:
    imdb_chart: top_shows
    collection_order: custom
    sort_title: "# 02 Top250"
    sync_mode: sync
    url_poster: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Posters/Charts/Top_250.JPG
    visible_home: false
    visible_shared: true
    visible_library: true
    schedule: monthly(1), monthly(15)
